<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N04S6B6" failures="2" tests="21" name="org.example.Test_Runner.TestRunner" time="180.630" errors="1" timestamp="2022-12-15T00:52:18 EET" skipped="0">
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="7.534"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="7.413"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="20.564"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="6.526"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="9.203"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="8.293"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="8.488"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="6.679"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="8.255"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="10.328"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="8.415">
    <error message="Index 1 out of bounds for length 1" type="java.lang.IndexOutOfBoundsException">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at org.example.Step_Definitions.D08_FollowUs_StepDefinitions.rss(D08_FollowUs_StepDefinitions.java:73)
at ✽.user should be directed to the website rss page(file:///D:/E-Commerce%20Website%20Project/E-Commerce_Website_Testing/src/main/resources/Features_Folder/F08_FollowUs.feature:17)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="8.214"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="6.401"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="20.040"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="8.094"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="6.782"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="5.925"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="5.994">
    <failure message="expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/nokia-lumia-1020] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.Step_Definitions.D07_HomeSliders_StepDefinitions.nokia_Page(D07_HomeSliders_StepDefinitions.java:25)
at ✽.user should be directed to iPhone page(file:///D:/E-Commerce%20Website%20Project/E-Commerce_Website_Testing/src/main/resources/Features_Folder/F07_Home_Sliders.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="6.155"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="5.288"/>
  <system-out/>
  <testcase classname="org.example.Test_Runner.TestRunner" name="runScenario" time="6.039">
    <failure message="expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/iphone-6] but found [https://demo.nopcommerce.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.example.Step_Definitions.D07_HomeSliders_StepDefinitions.iphone_Page(D07_HomeSliders_StepDefinitions.java:40)
at ✽.user should be directed to Nokia Lumia 1020 page(file:///D:/E-Commerce%20Website%20Project/E-Commerce_Website_Testing/src/main/resources/Features_Folder/F07_Home_Sliders.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- org.example.Test_Runner.TestRunner -->
